/* --- KAIGAN CHARACTER DATABASE v2.3 (Normalized) --- */

window.KaiganDatabase = {
    // ==========================================
    // MELLOW PIRATES
    // ==========================================
    "alva_": {
        name: "Alva",
        age: null,
        gender: "♀",
        tribe: null,
        birthday: null,
        homeland: null,
        height: null,
        weight: null,
        bloodType: null,
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#FFB6C1",
        bounty: "41040520",
        faction: "Pirate",
        crew: "Mellow Pirates",
        rank: "n/a",
        role: "Captain",
        alias: "N/A",
        alignment: null,
        native_sea: null,
        occupation: null,
        profession: [],
        fighting_style: [],
        portrait: "bounty_posters/alva.webp",
        fruit: ["Love-Love", "Mero-Mero"],
        fruit_tier: 1,
        fruit_desire: 100,
        acquisition: "Eaten",
        dki: "3000",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    "aestella_fukuhara": {
        name: "ᛖᛊᛏᛖᛚᚨ ᛞᛖᚠᚨ ᚠᚢᚲᚨᚺᚨᚱᚨ",
        age: 20,
        gender: "♀",
        tribe: "Lunarian",
        birthday: "02/29",
        homeland: "Elegia",
        height: "3'624'565'737 nm",
        weight: "684'219'883'197'183 ng",
        bloodType: "XF (RH+)",
        lunarianModeLabels: { highDurability: "Fortissimo", highSpeed: "Accelerando" },
        pTrait: null,
        sTrait: null,
        color: "#BB86FC",
        bounty: "0",
        faction: ["Pirate", "Revolutionary"],
        crew: "Mellow Pirates",
        rank: "Sergeant",
        role: ["Entertainer"],
        alias: "N/A",
        alignment: "Lawful Good",
        native_sea: "West Blue",
        occupation: "n/a",
        profession: [["Entertainer", 2]],
        fighting_style: [["Bladesmanship", 1, { tier_1: "Robust Blade" }]],
        portrait: "bounty_posters/aestella.webp",
        fruit: ["Sing-Sing", "???"],
        fruit_tier: 0,
        fruit_desire: 100,
        acquisition: "Story-Locked",
        dki: "3023",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: "110-419-SING",
        inventory: [{ id: "penancers" }, { id: "hairpin" }, { id: "Gsnail" }]
    },
    "kokone_fukuhara": {
        name: "Kokone Fukuhara",
        age: 18,
        gender: "♀",
        tribe: "Human",
        birthday: "08/31",
        homeland: "Wano-kuni",
        height: "158 cm",
        weight: "44.4521 kg",
        bloodType: "S (RH-)",
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#0eeadf",
        bounty: "0",
        faction: ["Pirate", "Revolutionary"],
        crew: "Mellow Pirates",
        rank: "Member",
        role: ["Cook", "Entertainer"],
        alias: "N/A",
        alignment: "True Neutral",
        native_sea: "New World",
        occupation: null,
        profession: [["Cook", 1], ["Entertainer", 2]],
        fighting_style: [],
        portrait: "bounty_posters/kokone.webp",
        fruit: ["Glint-Glint", "Pika-Pika"],
        fruit_tier: 0,
        fruit_desire: 20,
        acquisition: null,
        dki: "1490",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    "shreya": {
        name: "Shreya",
        age: null,
        gender: "♀",
        tribe: null,
        birthday: null,
        homeland: null,
        height: null,
        weight: null,
        bloodType: null,
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#360e64",
        bounty: "0",
        faction: "Pirate",
        crew: "Mellow Pirates",
        rank: "n/a",
        role: "Member",
        alias: "Eya",
        alignment: "Neutral Good",
        native_sea: "New World",
        occupation: "Infiltrator",
        profession: [["Infiltrator", 1]],
        fighting_style: [["Brutesmanship", 1]],
        portrait: "bounty_posters/shreya.webp",
        fruit: "n/a",
        fruit_tier: null,
        fruit_desire: null,
        acquisition: null,
        dki: "786",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    "zetsushi_sin": {
        name: "Zetsushi Sin",
        age: null,
        gender: null,
        tribe: null,
        birthday: null,
        homeland: null,
        height: null,
        weight: null,
        bloodType: null,
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#537235",
        bounty: "0",
        faction: "Pirate",
        crew: "Mellow Pirates",
        rank: "n/a",
        role: "Member",
        alias: "N/A",
        alignment: null,
        native_sea: null,
        occupation: null,
        profession: [],
        fighting_style: [],
        portrait: "bounty_posters/zetsushi.webp",
        fruit: "n/a",
        fruit_tier: null,
        fruit_desire: null,
        acquisition: null,
        dki: "950",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    "lian_hua": {
        name: "Lian",
        age: null,
        gender: null,
        tribe: null,
        birthday: null,
        homeland: null,
        height: null,
        weight: null,
        bloodType: null,
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#db87d4",
        bounty: "0",
        faction: "Pirate",
        crew: "Mellow Pirates",
        rank: "Rookie",
        role: "Member",
        alias: "N/A",
        alignment: "True Neutral",
        native_sea: "Paradise",
        occupation: ["Archeologist", "Merchant"],
        profession: [["Archeologist", 1], ["Merchant", 1]],
        fighting_style: [["Black-Leg", 1]],
        portrait: "bounty_posters/lian.webp",
        fruit: "n/a",
        fruit_tier: null,
        fruit_desire: null,
        acquisition: null,
        dki: "766",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    "tigress": {
        name: "Tigress",
        age: null,
        gender: "♀",
        tribe: null,
        birthday: null,
        homeland: null,
        height: null,
        weight: null,
        bloodType: null,
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#355E3B",
        bounty: "0",
        faction: "Pirate",
        crew: "Mellow Pirates",
        rank: "n/a",
        role: ["Vice Captain", "Navigator"],
        alias: "N/A",
        alignment: null,
        native_sea: "Calm-Belt",
        occupation: null,
        profession: [["Navigator", 1]],
        fighting_style: [["Weathermancy", 1]],
        portrait: "bounty_posters/tigress.webp",
        fruit: "n/a",
        fruit_tier: null,
        fruit_desire: null,
        acquisition: null,
        dki: "1500",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    "pepper": {
        name: "Pepper",
        age: 22,
        gender: "♀",
        tribe: "Mink",
        birthday: "04/04",
        homeland: "Zou",
        height: "5'2",
        weight: "112",
        bloodType: "S (RH-)",
        minkTraits: ["Feline Grace"],
        pTrait: "Liar of All Liars",
        sTrait: "The Oracle",
        color: "#cc8899",
        bounty: "0",
        faction: ["Pirate", "N/A"],
        crew: "Mellow Pirates",
        rank: "Rank",
        role: ["Archaeologist"],
        alias: "The Catermauler",
        alignment: "Chaotic Good",
        native_sea: "New World",
        occupation: "Archaeologist",
        profession: [["Archaeologist", 1]],
        fighting_style: [["Dragon Claw Fist", 1, { tier_1: "Dragon Claw Fist" }]],
        portrait: "bounty_posters/pepper.webp",
        fruit: ["N/A", "N/A"],
        fruit_tier: 0,
        fruit_desire: 0,
        acquisition: "N/A",
        dki: "963",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: "88-333-MEOW",
        inventory: [{ id: "item_id" }]
    },
    // ==========================================
    // ORCUS PIRATES
    // ==========================================
    "mani": {
        name: "Máni",
        age: null,
        gender: null,
        tribe: null,
        birthday: null,
        homeland: null,
        height: null,
        weight: null,
        bloodType: null,
        lunarianModeLabels: null,
        pTrait: null,
        sTrait: null,
        color: "#4A90E2",
        bounty: "0",
        faction: "Pirate",
        crew: "Orcus Pirates",
        rank: "n/a",
        role: "Member",
        alias: "N/A",
        alignment: null,
        native_sea: null,
        occupation: null,
        profession: [],
        fighting_style: [],
        portrait: "bounty_posters/mani.webp",
        fruit: "n/a",
        fruit_tier: null,
        fruit_desire: null,
        acquisition: null,
        dki: "3248",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: null
    },
    // ==========================================
    // REVOLUTIONARY AMRY
    // ==========================================
    "rolina_yeunova": {
        name: "Rolina D. Yeunova",
        age: 16,
        gender: "♀",
        tribe: "Mink",
        birthday: "02/29",
        homeland: "Weatheria",
        height: "1'549'463'728 nm",
        weight: "52'146'897'352'491 ng",
        bloodType: "XF (RH+)",
        minkTraits: ["Barometric Instinct", "Leporidae"],
        pTrait: "Demon of Mokomo",
        sTrait: null,
        color: "#A0E7E5",
        bounty: "0",
        faction: "Revolutionary",
        crew: "Grand Division",
        rank: "Officer",
        role: "Member",
        alias: "N/A",
        alignment: "Lawful Good",
        native_sea: "White-White Sea",
        occupation: "n/a",
        profession: [["Navigator", 0]],
        fighting_style: [["Weathermancy", 3]],
        portrait: "bounty_posters/rolina.webp",
        fruit: ["Snow-Snow", "Yuki-Yuki"],
        fruit_tier: 1,
        fruit_desire: 100,
        acquisition: "Force-Fed",
        dki: "2349",
        haki: { armament: 0, observation: 0, conquerors: 0 },
        tsNumber: null,
        inventory: [{id: "climatact"}, { id: "pclimatact" }]
    }
};
